version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/crn
      - public-data:/crn/public
      - tmp-data:/crn/tmp
      - log-data:/crn/log
    depends_on:
      - db

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/crn/public
      - tmp-data:/crn/tmp
    ports:
      - 80:80
    depends_on:
      - app
      
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: